apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-dev
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-dev
  template:
    metadata:
      labels:
        app: python-app-dev
    spec:
      containers:
        - name: app
          image: maheellakshan/python-cicd:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: VERSION
              value: "0.0.0"
