apiVersion: v1
kind: Service
metadata:
  name: python-app-dev
  namespace: development
spec:
  type: NodePort
  selector:
    app: python-app-dev
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
