apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-prod
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app-prod
  template:
    metadata:
      labels:
        app: python-app-prod
    spec:
      containers:
        - name: app
          image: maheellakshan/python-cicd:3.4.1-rc-prod
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: VERSION
              value: "3.4.1" # VERSION
