apiVersion: v1
kind: Service
metadata:
  name: python-app-prod
  namespace: production
spec:
  type: NodePort
  selector:
    app: python-app-prod
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30082
