apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-qa
  labels:
    app: python-app-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-qa
  template:
    metadata:
      labels:
        app: python-app-qa
    spec:
      containers:
        - name: python-app
          image: maheellakshan/python-cicd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: qa
