apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-qa
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-qa
  template:
    metadata:
      labels:
        app: python-app-qa
    spec:
      containers:
        - name: app
          image: maheellakshan/python-cicd:4.4.1-rc-qa
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "qa"
            - name: VERSION
              value: "4.4.1" # VERSION
