apiVersion: v1
kind: Service
metadata:
  name: python-app-qa
  namespace: qa
spec:
  type: NodePort
  selector:
    app: python-app-qa
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081
